<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categoryIds = Category::pluck('id', 'slug');
        $brandIds = Brand::pluck('id', 'slug');

        $products = [
            [
                'name' => 'Professional Stand Mixer 5.5L',
                'slug' => 'professional-stand-mixer-5-5l',
                'description' => 'Powerful 5.5L stand mixer with 10 speeds, tilt-head design, and planetary mixing action. Includes flat beater, dough hook, and wire whip.',
                'price' => 5499900,
                'stock' => 25,
                'image' => 'default-product.jpg',
                'status' => true,
                'category_slug' => 'kitchen-appliances',
                'brand_slug' => 'kitchenaid',
            ],
            [
                'name' => 'High-Performance Blender 1200W',
                'slug' => 'high-performance-blender-1200w',
                'description' => 'Professional-grade blender with 1200W motor, 2L pitcher, and 5 speed settings. Ideal for smoothies, soups, and crushing ice.',
                'price' => 2999900,
                'stock' => 40,
                'image' => 'default-product.jpg',
                'status' => true,
                'category_slug' => 'kitchen-appliances',
                'brand_slug' => 'kitchenaid',
            ],
            [
                'name' => 'Digital Air Fryer Oven 12L',
                'slug' => 'digital-air-fryer-oven-12l',
                'description' => '12L digital air fryer with 8 presets, convection baking, and rotisserie function. Cook crispy food with 85% less oil.',
                'price' => 3999900,
                'stock' => 30,
                'image' => 'default-product.jpg',
                'status' => true,
                'category_slug' => 'kitchen-appliances',
                'brand_slug' => 'cuisinart',
            ],
            [
                'name' => 'Stainless Steel Cookware Set 10-Piece',
                'slug' => 'stainless-steel-cookware-set-10-piece',
                'description' => 'Complete 10-piece cookware set including fry pans, saucepans, and stockpot with tempered glass lids. Suitable for all stovetops.',
                'price' => 4999900,
                'stock' => 15,
                'image' => 'default-product.jpg',
                'status' => true,
                'category_slug' => 'cookware',
                'brand_slug' => 'cuisinart',
            ],
            [
                'name' => 'Enameled Cast Iron Dutch Oven 6QT',
                'slug' => 'enameled-cast-iron-dutch-oven-6qt',
                'description' => 'Premium enameled cast iron dutch oven with tight-fitting lid. Ideal for braising, roasting, baking, and slow cooking.',
                'price' => 4499900,
                'stock' => 20,
                'image' => 'default-product.jpg',
                'status' => true,
                'category_slug' => 'cookware',
                'brand_slug' => 'le-creuset',
            ],
            [
                'name' => 'Cast Iron Skillet 12-Inch',
                'slug' => 'cast-iron-skillet-12-inch',
                'description' => 'Pre-seasoned 12-inch cast iron skillet with helper handle. Oven safe, perfect for searing, frying, and baking.',
                'price' => 899900,
                'stock' => 60,
                'image' => 'default-product.jpg',
                'status' => true,
                'category_slug' => 'cookware',
                'brand_slug' => 'lodge',
            ],
            [
                'name' => 'Non-Stick Frying Pan Set 3-Piece',
                'slug' => 'non-stick-frying-pan-set-3-piece',
                'description' => 'Set of 8-inch, 10-inch, and 12-inch non-stick frying pans with riveted handles and durable titanium coating.',
                'price' => 1799900,
                'stock' => 35,
                'image' => 'default-product.jpg',
                'status' => true,
                'category_slug' => 'cookware',
                'brand_slug' => 'lodge',
            ],
            [
                'name' => 'Chef Knife 8-Inch with Forged Blade',
                'slug' => 'chef-knife-8-inch-forged-blade',
                'description' => 'Professional 8-inch chef knife crafted from high-carbon stainless steel with ergonomic handle. Rockwell hardness 58-60.',
                'price' => 2499900,
                'stock' => 45,
                'image' => 'default-product.jpg',
                'status' => true,
                'category_slug' => 'kitchen-appliances',
                'brand_slug' => 'zwilling',
            ],
            [
                'name' => 'Knife Sharpening Stone Set',
                'slug' => 'knife-sharpening-stone-set',
                'description' => 'Dual-grit 1000/6000 whetstone with non-slip bamboo base. Includes honing guide and angle guide for professional sharpening.',
                'price' => 699900,
                'stock' => 50,
                'image' => 'default-product.jpg',
                'status' => true,
                'category_slug' => 'kitchen-appliances',
                'brand_slug' => 'zwilling',
            ],
            [
                'name' => 'Stoneware Dinner Set 16-Piece',
                'slug' => 'stoneware-dinner-set-16-piece',
                'description' => 'Elegant 16-piece stoneware dinner set for 4, including dinner plates, salad plates, bowls, and mugs. Microwave and dishwasher safe.',
                'price' => 2999900,
                'stock' => 20,
                'image' => 'default-product.jpg',
                'status' => true,
                'category_slug' => 'tableware',
                'brand_slug' => 'le-creuset',
            ],
            [
                'name' => 'Porcelain Serving Platter 14-Inch',
                'slug' => 'porcelain-serving-platter-14-inch',
                'description' => 'Large 14-inch porcelain serving platter with elegant raised rim. Perfect for roasts, fish, and appetizer displays.',
                'price' => 899900,
                'stock' => 30,
                'image' => 'default-product.jpg',
                'status' => true,
                'category_slug' => 'tableware',
                'brand_slug' => 'le-creuset',
            ],
            [
                'name' => 'Wine Glasses Set of 6',
                'slug' => 'wine-glasses-set-of-6',
                'description' => 'Set of 6 elegant crystal wine glasses with thin rims and long stems. Capacity 450ml, dishwasher safe.',
                'price' => 1299900,
                'stock' => 40,
                'image' => 'default-product.jpg',
                'status' => true,
                'category_slug' => 'tableware',
                'brand_slug' => 'oxo',
            ],
            [
                'name' => 'Silicone Baking Mat Set 2-Piece',
                'slug' => 'silicone-baking-mat-set-2-piece',
                'description' => 'Set of 2 non-stick silicone baking mats with measurement guides. Reusable, oven safe to 480°F, and dishwasher safe.',
                'price' => 499900,
                'stock' => 75,
                'image' => 'default-product.jpg',
                'status' => true,
                'category_slug' => 'baking-tools',
                'brand_slug' => 'oxo',
            ],
            [
                'name' => 'Muffin Pan 12-Cup Non-Stick',
                'slug' => 'muffin-pan-12-cup-non-stick',
                'description' => 'Heavy-duty 12-cup muffin pan with professional non-stick coating. Even heat distribution for perfectly baked muffins.',
                'price' => 399900,
                'stock' => 55,
                'image' => 'default-product.jpg',
                'status' => true,
                'category_slug' => 'baking-tools',
                'brand_slug' => 'cuisinart',
            ],
            [
                'name' => 'Measuring Cup Set 5-Piece',
                'slug' => 'measuring-cup-set-5-piece',
                'description' => 'Set of 5 measuring cups from 1/4 cup to 1 cup with clear markings and ergonomic handles. Made of durable polypropylene.',
                'price' => 299900,
                'stock' => 80,
                'image' => 'default-product.jpg',
                'status' => true,
                'category_slug' => 'baking-tools',
                'brand_slug' => 'oxo',
            ],
            [
                'name' => 'Stainless Steel Mixing Bowl Set 4-Piece',
                'slug' => 'stainless-steel-mixing-bowl-set-4-piece',
                'description' => 'Set of 4 stainless steel mixing bowls from 1.5L to 5L with non-slip bases. Nesting design for easy storage.',
                'price' => 899900,
                'stock' => 40,
                'image' => 'default-product.jpg',
                'status' => true,
                'category_slug' => 'baking-tools',
                'brand_slug' => 'kitchenaid',
            ],
            [
                'name' => 'Airtight Food Storage Container Set 10-Piece',
                'slug' => 'airtight-food-storage-container-set-10-piece',
                'description' => 'Set of 10 glass food storage containers with airtight locking lids. Oven, microwave, freezer and dishwasher safe.',
                'price' => 1999900,
                'stock' => 35,
                'image' => 'default-product.jpg',
                'status' => true,
                'category_slug' => 'food-storage',
                'brand_slug' => 'pyrex',
            ],
            [
                'name' => 'Glass Meal Prep Container Set 6-Piece',
                'slug' => 'glass-meal-prep-container-set-6-piece',
                'description' => 'Set of 6 partitioned glass meal prep containers with leak-proof lids. Perfect for portion control and weekly meal planning.',
                'price' => 899900,
                'stock' => 50,
                'image' => 'default-product.jpg',
                'status' => true,
                'category_slug' => 'food-storage',
                'brand_slug' => 'pyrex',
            ],
            [
                'name' => 'Kitchen Jar Set 3-Piece with Bamboo Lids',
                'slug' => 'kitchen-jar-set-3-piece-bamboo-lids',
                'description' => 'Set of 3 glass storage jars with bamboo lids in 1L, 1.5L, and 2L sizes. Perfect for pasta, rice, flour, and snacks.',
                'price' => 699900,
                'stock' => 45,
                'image' => 'default-product.jpg',
                'status' => true,
                'category_slug' => 'food-storage',
                'brand_slug' => 'oxo',
            ],
            [
                'name' => 'Enameled Cast Iron Braiser 3.5QT',
                'slug' => 'enameled-cast-iron-braiser-3-5qt',
                'description' => 'Premium enameled cast iron braiser with self-basting lid. Perfect for slow braising, roasting, and simmering.',
                'price' => 4999900,
                'stock' => 10,
                'image' => 'default-product.jpg',
                'status' => true,
                'category_slug' => 'cookware',
                'brand_slug' => 'staub',
            ],
        ];

        foreach ($products as $product) {
            Product::firstOrCreate(
                ['slug' => $product['slug']],
                [
                    'name' => $product['name'],
                    'description' => $product['description'],
                    'price' => $product['price'],
                    'stock' => $product['stock'],
                    'image' => $product['image'],
                    'status' => $product['status'],
                    'category_id' => $categoryIds[$product['category_slug']] ?? null,
                    'brand_id' => $brandIds[$product['brand_slug']] ?? null,
                ]
            );
        }
    }
}
